[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first'
sort_imports = true

[profile.default]
solc_version = '0.8.23'
src = 'solidity'
test = 'solidity/test'
out = 'out'
libs = ["node_modules", "lib"]
optimizer_runs = 10_000

[profile.optimized]
via_ir = true
out = 'out-via-ir'

[profile.test]
via_ir = true
out = 'out-via-ir'
src = 'solidity/test'

[profile.docs]
src = 'solidity/interfaces/'

[fuzz]
runs = 1000

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
arbitrum = "${ARBITRUM_RPC}"
optimism = "${OPTIMISM_RPC}"
bsc = "${BSC_RPC}"
polygon = "${POLYGON_RPC}"
base = "${BASE_RPC}"
sepolia = "${SEPOLIA_RPC}"
arb_sepolia = "${ARB_SEPOLIA_RPC}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY_MAINNET}" }
arbitrum = { key = "${ETHERSCAN_API_KEY_ARB}" }
optimism = { key = "${ETHERSCAN_API_KEY_OPTIMISM}" }
base = { key = "${ETHERSCAN_API_KEY_BASE}" }
bsc = { key = "${ETHERSCAN_API_KEY_BSC}" }
polygon = { key = "${ETHERSCAN_API_KEY_POLYGON}" }
